version: '3'

services:
  client:
    build: ./client
    ports:
      - "80:80"
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "3005:3005"
    environment:
      - MONGODB_URI=Your Mongo URI
      - PORT=3005
      - SECRET=Your JWT secret
      - CLOUDINARY_NAME=From your cloudinary dashboard
      - CLOUDINARY_API_KEY=From your cloudinary dashboard
      - CLOUDINARY_API_SECRET=From your cloudinary dashboard
      - UPLOAD_PRESET=Folder/preset name from your cloudinary account (OPTIONAL)